### PR TITLE
Code tidy: fix lgtm alert

### PR DESCRIPTION
**Pull request by m-holger**
…ntHelper

### CODE REVIEW

**Comment by m-holger** [comment]
I pushed this PR purely to run LGTM check.

**Comment by m-holger** [comment]
The PR probably improves performance, but to a highly insignificant degree (of the order of less than 0.06%).

I have looked at a number of other instances where "good practice" suggests that parameters should be passed as const& rather than by value. A number of them showed a more significant impact - however, in none of the cases was the impact in the desired direction!

Contrary to what the lgtm analysis check run suggests, this commit fixes the existing alert.

**Comment by jberkenbilt** [comment]
I appreciate the analysis. I'd rather not take this -- I don't want to add code that replaces default behavior with manual memory management (using a pointer for the iterator). I'll just drop the lgtm banner. Performance is important, but maintainability is more important except in highly critical areas of code or when performance is particularly bad.

**Comment by jberkenbilt** [comment]
I'd consider a PR that only changes copies to const& in function calls without the changes to the iterator.

**Comment by m-holger** [comment]
I do not think this PR has any merit other than managing lgtm analyses.

For performance it seems to me that the existing compilers do a very decent job and on balance are better at optimizing code than I am.

I'd suggest you simply close this PR.

Hopefully QPDFObjectHandle will shrink in the future and the problem will go away by itself.

As an aside, the more I learn about lgtm the less impressed I am, and I do not think their ratings are meaningful.

**Comment by jberkenbilt** [comment]
Thanks again for your analysis.

**Pull request closed without merging**
