### PR TITLE
Refactor Pl_QPDFTokenizer

### PR DESCRIPTION
**Pull request by m-holger**
Reduce unnecessary copying for performance reasons

### CODE REVIEW

**Comment by m-holger** [comment]
@jberkenbilt  , is there any reason for the content normalizer to preserve trailing spaces and blank lines?

**Comment by jberkenbilt** [comment]
That's a tough one. My impulse is that it should leave them alone. I feel like I kind of want to know if the original file has trailing whitespace and blank lines. It's been a while, but I have encountered files with some uncompressed content that uses trailing spaces for padding purposes for naive, text-based form-filling. Back years ago, there was online greeting card thing we used to use that generated PDFs that way, and I might not have known if qdf stripped that stuff. Of course, people can use regular uncompress without qdf, but qdf has behaved a certain way for a long time, I don't think we should gratuitously change it.

**Comment by m-holger** [comment]
Ok

**Review by jberkenbilt — APPROVED** [review]
These kinds of changes are hard to review....it's easy to insert subtle errors. I reviewed this pretty carefully and didn't find anything wrong. Hopefully if there are any memory errors (which I don't think there are), the fuzzer will catch them.

**Pull request merged**
