### PR TITLE
Add QPDFWriter::getRenumberedObjGen() and QPDFWriter::getWrittenXRefTable()

### PR DESCRIPTION
**Pull request by trueroad**
These methods are useful for making PDF digitally signing tool (https://github.com/qpdf/qpdf/pull/369#issuecomment-536241488).

### CODE REVIEW

**Comment by jberkenbilt** [comment]
I would be nice if the format of the xref table returned were the same as the one from QPDF. Unfortunately, QPDFWriter uses int as the map key, which is an optimization stemming from the fact that QPDFWriter never creates objects with generation != 0. I wonder whether we could construct a map from QPDFObjGen for consistency. It would make for a cleaner API. I'm writing this comment without looking at the other PR. Hopefully what I'm saying is correct and makes sense.

**Comment by trueroad** [comment]
Thank you for your advice.
I've fixed it.

**Comment by trueroad** [comment]
I've added the tests for QPDFWriter::getRenumberedObjGen().
For the tests for QPDFWriter::getWrittenXRefTable(), I think that QPDF::getXRefTable() in #369 is needed.
If #369 is merged, I will write the tests.

**Comment by jberkenbilt** [comment]
As mentioned earlier, I want to merge everything together. If needed, rebase 370 on top of 369 so you can write the tests. This is the reason that I'd rather see everything in one PR with a separate commit for each change.

**Comment by trueroad** [comment]
I've added all tests for all changes (#367, #368, #369, #370, #372).
If I understand correctly, I've fixed the tests as you described.

If you want to fix the changes in this pull request, please comment on this pull request.
If you want to fix the tests, please fix it.

If you satisfy, I'll make integrated pull request that contains all pull requests.

**Comment by jberkenbilt** [comment]
Incorporated by #376

**Pull request closed without merging**
