### PR TITLE
Alternative fix for #422

### PR DESCRIPTION
**Pull request by tomty89**
Instead of not passing `-rpath $(libdir)` to libtool at all, only empty `hardcode_libdir_flag_spec{,_CXX}` that consist of "`rpath`" and `runpath_var{,_CXX}`. The former approach appears to prevent proper `libqpdf.la` generation and `libqpdf.lai` creation.

Ref.: https://github.com/termux/termux-packages/commit/a29657b770be854cabd2123ea86b6a2ac3cc1f36

### CODE REVIEW

**Comment by jberkenbilt** [comment]
I think this looks fine, but I'll admit to not fully understanding exactly what the underlying issue is. I'll have to review the previous change and see what the difference is with the previous change. I will make sure I study it before whatever the next release is. I think I'm going to have to carve out some time for a 10.3.3 release as minor issues are piling up.

**Comment by jberkenbilt** [comment]
If you have some kind of formula I can use to know whether a specific fix does or doesn't solve the underlying problem, it would be very helpful if you can provide it so I can update my notes. I have no issues with something like trying to create an RPM from a fedora docker image or something along those lines. My native environment is Ubuntu/Debian, but I've spent lots of times in the RedHat/Fedora/CentOS world as well and have good albeit outdated familiarity with that ecosystem.

**Comment by tomty89** [comment]
Well, I am not exactly familiar with the DT_RPATH stuff, but it *seems* to me that the OP probably bumped into the problem because he  (unnecessarily?) used `--libdir /usr/lib64` for `./configure`. When I test in Arch, the rpath link flags are not actually used if `--libdir` is not set or set to `/usr/lib`, the implicit default when `--prefix` is `/usr`. (It probably has nothing to do with what the default is in `./configure`, but rather what was set as the default library path when `ld` or so was built.)

With that said, the OP (the part that one might want a way to disable the emission of DT_RPATH) still stands when for example one wants to build with prefix like `/usr/local`. I tested the PR with such case and it succeeded to prevent the executables from having DT_RPATH (confirmed with `readelf --dynamic` in addition to the build log).

**Comment by jberkenbilt** [comment]
Sorry, what is `OP`?

**Comment by tomty89** [comment]
Ahh sorry. I mean like the original poster / problem of #422.

**Comment by jberkenbilt** [comment]
Sorry for the long delay. This patch modifies variables that are set inside of macros that I don't control, so I'm not willing to accept it as is since I think it will be too fragile. Maybe you can explain exactly what the issue is that you are trying to solve.

**Comment by tomty89** [comment]
> This patch modifies variables that are set inside of macros that I don't control, so I'm not willing to accept it as is since I think it will be too fragile.

Yeah, it's kind of fragile. I think it's at least partly because libtool is more or less dead (in terms of development) and messy anyway. So everything can only go downstream.

> Maybe you can explain exactly what the issue is that you are trying to solve.

The problem is you sort of misunderstood what `-rpath` does in `ltmain.sh. (Well, to be fair, it does not separate things fine enough from the beginning.) The switch does not (only) prevent what was unwanted / complained (i.e. `DT_RPATH` / `DT_RUNPATH`) in #422. Rather its value is also crucial for the generation of `libqpdf.la{,i}`. The problem is only triggered when `--prefix` is not `/usr` though.

**Comment by jberkenbilt** [comment]
I think I'm going to switch qpdf's build to cmake for version 11. This issue as well as some issues with the Windows build will probably just go away if I do that.

**Comment by jberkenbilt** [comment]
I've come far enough on making qpdf build with cmake that I'm firmly committing to it for qpdf 11 and will therefore close this issue. I have verified that cmake handles rpath correctly at installation time.

**Pull request closed without merging**
