### PR TITLE
Fix null pointer issue on array copy

### PR DESCRIPTION
**Pull request by jberkenbilt**
@m-holger FYI

### CODE REVIEW

**Comment by m-holger** [comment]
Sorry about this

**Comment by jberkenbilt** [comment]
> Sorry about this

No worries. I could have caught it, and the test suite should have covered this case. Maybe I need to do something about coverage analysis beyond QTC, which is good, but perhaps insufficient. Then we could check easily to see whether some code we are changing is covered.

**Comment by m-holger** [comment]
Perhaps it would also be worth considering freezing the code for a couple of days before releasing.

**Comment by jberkenbilt** [comment]
Yeah. I usually give it overnight at least. With more complex changes, it's worth a little longer. Though I don't think very many people use unreleased versions. As you know, I watch the code freeze cycle of debian and Ubuntu and am extra careful with things that are going into LTS releases. I'm not sure what version will go into 24.04, but I doubt it will have the pages work in it. We'll see how much more time I can get for this. I think I have at least another week or two before I get pulled back into my normal work.

**Pull request merged**
