### PR TITLE
Add C API qpdf_oh_free_buffer to release memory allocated by stream data functions

### PR DESCRIPTION
**Pull request by mslichao**
Add C API qpdf_free_buffer to release memory allocated by stream data functions

### CODE REVIEW

**Comment by m-holger** [comment]
Very good attempt.

Could you change the name to  qpdf_oh_free_buffer. Thanks.

**Comment by mslichao** [comment]
> Very good attempt.
> 
> Could you change the name to qpdf_oh_free_buffer. Thanks.

Sure, renamed.

**Comment by mslichao** [comment]
@m-holger I don't have permission to merge this PR. Could you help with it?

**Comment by m-holger** [comment]
@mslichao , thanks for the contributions (and for adding the change log entry).

I will merge the PR as is and doe the tweaks to the comments afterwards.

**Pull request merged**
