### PR TITLE
Code clean up: use range-style for loops wherever possible

### PR DESCRIPTION
**Pull request by m-holger**
Remove variables obsoleted by commit 4f24617.

### CODE REVIEW

**Comment by jberkenbilt** [comment]
Thanks -- I started doing this but didn't get through it. I'll scrutinize this and most likely accept it.

**Comment by jberkenbilt** [comment]
There's a merge conflict you might want to fix after my latest push. Looks like maybe I had made one of the changes you also made in my recent work. At this moment, all my changes are in main, so it's a good time to squeeze this in. If you don't get to it, I'll take care of the merge conflict.

**Comment by jberkenbilt** [comment]
(I'm still doing active work -- I just pushed the most recent increment.)

**Comment by m-holger** [comment]
Rebased to latest main.

**Comment by jberkenbilt** [comment]
> Rebased to latest main.

Thanks! I should have time to merge it later today or sometime this weekend.

**Pull request merged**
