### PR TITLE
CIFuzz Dog Food

### PR DESCRIPTION
**Pull request by Leo-Neat**
OSS-Fuzz was wondering if qpdf would dogfood CIFuzz, a new feature being rolled out in OSS-Fuzz. It allows for pull requests to be fuzzed in CI using fuzz targets enabled in OSS-Fuzz. It will be active in dry_run mode meaning that it will never fail. Documentation for this feature can be found [here](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). Let us know if you have any questions!

### CODE REVIEW

**Comment by jberkenbilt** [comment]
Yes, happy to help out in this way. I'm not sure why tests are failing right now. Looks like it might be a transient issue. I also want to make sure that, with both github actions and azure pipelines, it's obvious what's what, so I may want to tweak the workflows file. Do I have to do anything to enable actions?

**Comment by Leo-Neat** [comment]
@jberkenbilt Sounds great! You don't have to do anything else to enable actions.  Once the  main.yml file is added to your  workflow directory, the test will be run  on pull requests automatically.

**Comment by jberkenbilt** [comment]
CI is looking good. I'll check it later tonight or over the weekend and merge if good. I guess we hit some hiccup on Azure pipelines yesterday.

**Comment by jberkenbilt** [comment]
@Leo-Neat Right now, #283 is running this action. This is my standing pull request that I update to get CI before I push to master.

**Pull request merged**
