### PR TITLE
Add new virtual method QPDFObject::getStringValue

### PR DESCRIPTION
**Pull request by m-holger**
Avoid dynamic casting.

I see an improvement of approx 0.5%.

### CODE REVIEW

**Comment by m-holger** [comment]
@jberkenbilt  The CI failure doesn't look to me to be a problem with the commit. 

```
+ sha256sum distribution/qpdf-11.2.1-doc-ci.zip
4cf4055d2a4f4918b801e039e8e27f88454d94d1f14bb99a4344d7921502809a  distribution/qpdf-11.2.1-doc-ci.zip
Traceback (most recent call last):
  File "/home/runner/work/qpdf/qpdf/build-scripts/download-external-libs", line 37, in <module>
    [(r['tag_name'], r) for r in releases
  File "/home/runner/work/qpdf/qpdf/build-scripts/download-external-libs", line 38, in <listcomp>
    if r['prerelease'] is False],
TypeError: string indices must be integers
```

**Comment by jberkenbilt** [comment]
> The CI failure doesn't look to me to be a problem with the commit.

Looks like a transient failure with github. I reran the jobs.

**Comment by m-holger** [comment]
> Looks like a transient failure with github. I reran the jobs.

Thanks

> I see an improvement of approx 0.5%.

Or it could be 1.5%. Who knows. I feel reasonably confident that 11.3 will be over 1.35 times faster than 11.2 and well over twice as fast as 10.6 (excluding JSON tests) but for anything under 1% over 20 repetitions  the significance of what looks like an improvement is difficult to judge. I think I'll open a discussion topic on performance testing.

**Comment by jberkenbilt** [comment]
> I think I'll open a discussion topic on performance testing.

There's an existing discussion on Windows performance. You might want to mention your discussion there.

**Review by jberkenbilt — APPROVED** [review]
Nice simplification.

**Pull request merged**
