### PR TITLE
Implement PNG filters

### PR DESCRIPTION
**Pull request by rojasc**
This implements the other 3 filters (Sub, Average, Paeth) when decoding stream.

I'm sorry i didn't add any tests because I didn't know how to submit sample PDF. When I was writing this, I used a set of set of PDF from a client, but I couldn't not include them here. 

I figured I'll send a pull request because I'm sure others could benefit from this as well.

### CODE REVIEW

**Comment by jberkenbilt** [comment]
This is a huge help as implementing the rest of the PNG filters is one of the next up things for me to do and a feature that is requested. I have some test data that I can use. Next time I have a chance to work on qpdf, I will review this and either accept it as is or modify it. I'll make sure you get credit for the work. Thanks!

**Comment by jberkenbilt** [comment]
Also, don't worry about the travis CI failures. I haven't actually got that fully set up yet.

**Comment by rojasc** [comment]
Sounds great. Happy to contribute.

**Comment by jberkenbilt** [comment]
I have taken your commits, squashed them, cleaned up some comments and whitespace, and incorporated them into my png-filters branch. I will add tests and update other places in the code the "know" that the other filters are not implemented. When I'm done, I'll close your pull request with a note that the changes have been accepted. I've left your name on the commit that introduces the code changes and will credit you in the ChangeLog. Thanks!

**Comment by jberkenbilt** [comment]
Turns out there were a few bugs in the implementation, but I have fixed them in my branch. I still have to add automated testing, but manual testing using the files in #83 plus considerable inspection of binary data suggests everything is okay. The bugs were not in the algorithms but in the memory handling and handling of parameters. Also, there were other changes required to the library to make use of the new functionality. In any case, I have fully incorporated your contribution into my branch, and it will be in the next released version. Thanks very much for doing this.

**Comment by jberkenbilt** [comment]
If you're interested in an early peek at the changes I made, you can check the png-filters branch of the jberkenbilt/qpdf fork. Note that I will be rebasing and force pushing several times before this goes into master, and that as of this moment, I have not yet added test cases, though I have manually tested using the images from #83.

**Pull request closed without merging**
