### PR TITLE
Add new QPDFObjectHandle::getValueAs... accessors

### PR DESCRIPTION
**Pull request by m-holger**

### CODE REVIEW

**Comment by jberkenbilt** [comment]
@m-holger Sorry to surprise you with getPointer() -> get(). Otherwise, looks good at a glance -- I will do a thorough review once you fix that.

**Review by jberkenbilt — APPROVED** [review]
I'm approving this conditionally upon changing away from the newly deprecated getPointer() call. If you happen to not get to it before I'm ready to release, I'll just take this commit, change getPointer() to get(), and amend with your email on it.

**Comment by m-holger** [comment]
Ah life - full of little surprises.

**Comment by jberkenbilt** [comment]
Thank you for taking care of this!

**Pull request merged**
