### PR TITLE
Rationalise interface between QPDFObject, QPDFObjectHandle and QPDF

### PR DESCRIPTION
**Pull request by m-holger**
Centralise casting of QPDFObjects and reduce repeated dereferencing.

### CODE REVIEW

**Comment by m-holger** [comment]
I don't like the name asStreamWithAssert. Any sugggestions?

**Comment by jberkenbilt** [comment]
There are too many changes here for me to accept this without a discussion. I have scanned through the code, but I will have to do a more thorough review so I can try to figure out what you're trying to accomplish here. There are things that look like temporary code too but I have to inspect more carefully.

**Comment by m-holger** [comment]
These are bits and pieces on the way to #726 which I felt would make sense even if you decided against splitting QPDFObject.

I put them into a single PR because of merge conflicts. Once you decide which ones you like I will do individual PRs in sequence.

We can discuss the individual commits later.  (Dinner time over here)

**Comment by m-holger** [comment]
Not worth considering at this time.

**Pull request closed without merging**
